routes/web.php
<?php

use App\Http\Controllers\ProductoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('producto', ProductoController::class);

app/Models/Producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Producto;
use Illuminate\Http\Request;

class ProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $productos = Producto::latest('fecha_crea')->paginate(10);
        return view('producto.index', [
            "productos" => $productos,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $producto = new Producto;

        return view('producto.create', [
            'producto' => $producto,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $atributos = request()->validate([
            'nombre'       => 'required',
            'referencia'     => 'required',
            'precio'  => 'required',
            'peso'             => 'required',
            'categoria'  => 'required',
            'stock'  => 'required',
            'fecha_crea'  => 'required',
            'fecha_ultima_venta'  => 'required',
        ]);

        Producto::create([
            'nombre'   => $request->nombre,
            'referencia' => $request->referencia,
            'precio'  => $request->precio,
            'peso'             => $request->peso,
            'categoria'       => $request->categoria,
            'stock'   => $request->stock,
            'fecha_crea'    => $request->fecha_crea,
            'fecha_ultima_venta' => $request->fecha_ultima_venta,
        ]);

//        Order::create(request->all());
//        session()->flash('success', 'Registro creado exitosamente');
        return redirect('producto')->with('success', 'Producto registrado exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function show(Producto $producto)
    {
        return view('producto.show', [
            'producto' => $producto,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function edit(Producto $producto)
    {
        return view('producto.edit', [
            'producto' => $producto,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Producto $producto)
    {
        $atributos = request()->validate([
            'nombre'       => 'required',
            'referencia'     => 'required',
            'precio'  => 'required',
            'peso'             => 'required',
            'categoria'  => 'required',
            'stock'  => 'required',
            'fecha_crea'  => 'required',
            'fecha_ultima_venta'  => 'required',
        ]);

        $producto->update($atributos);

//        session()->flash('success', 'Registro actualizado exitosamente');
        return redirect('producto')->with('success', 'Producto actualizado exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Producto $producto)
    {
        $producto->delete();
        return redirect('producto')->with('success', 'Producto eliminado exitosamente');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    
    <title>@yield('title', config('app.name', 'Konecta'))</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <!-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> -->
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
    <div id="app" class="container">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Konecta') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">

            @if( session()->has('success'))
                <p class='alert alert-success'>{{ session('success') }}</p>
            @endif

            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/producto/create.blade.php
@extends('layouts.app')

@section('title', 'Crear Producto')

@section('content')

<h1>Crear Producto</h1>

    <form action="{{ url('producto') }}" method="POST">
        @csrf

        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" placeholder="Nombre" value="{{ old('nombre',$producto->nombre) }}" class='form-control'>
            @error('nombre')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="referencia">Referencia</label>
            <input type="text" name="referencia" placeholder="Referencia" value="{{ old('referencia', $producto->referencia) }}" class='form-control'>
            @error('referencia')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="precio">Precio</label>
            <input type="text" name="precio" placeholder="Precio" value="{{ old('precio', $producto->precio) }}" class='form-control'>
            @error('precio')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="peso">Peso</label>
            <input type="text" name="peso" placeholder="Peso" value="{{ old('peso', $producto->peso) }}" class='form-control'>
            @error('peso')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="categoria">Categoría</label>
            <input type="text" name="categoria" placeholder="Categoría" value="{{ old('categoria', $producto->categoria) }}" class='form-control'>
            @error('categoria')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="stock">Stock</label>
            <input type="text" name="stock" placeholder="Stock" value="{{ old('stock', $producto->stock) }}" class='form-control'>
            @error('stock')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="fecha_crea">Fecha Crea</label>
            <input type="text" name="fecha_crea" placeholder="Fecha Crea" value="{{ old('fecha_crea', $producto->fecha_crea) }}" class='form-control'>
            @error('fecha_crea')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="fecha_ultima_venta">Fecha última venta</label>
            <input type="text" name="fecha_ultima_venta" placeholder="Fecha última venta" value="{{ old('fecha_ultima_venta', $producto->fecha_ultima_venta) }}" class='form-control'>
            @error('fecha_ultima_venta')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <input type="submit" value="Enviar" name="enviar" class='form-control btn btn-success'>
        </div>
    </form>
@endsection

resources/views/producto/edit.blade.php
@extends('layouts.app')

@section('title', 'Editar Producto')

@section('content')

<h1>Editar Producto <strong>{{ $producto->nombre }}</strong></h1>

<form action="{{ url('/producto/' . $producto->id) }}" method="post">
    @csrf
    {{ method_field('PATCH') }}
    @include('producto.form')
</form>

@endsection

resources/views/producto/form.blade.php
<div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" placeholder="Nombre" value="{{ old('nombre',$producto->nombre) }}" class='form-control'>
            @error('nombre')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="referencia">Referencia</label>
            <input type="text" name="referencia" placeholder="Referencia" value="{{ old('referencia', $producto->referencia) }}" class='form-control'>
            @error('referencia')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="precio">Precio</label>
            <input type="text" name="precio" placeholder="Precio" value="{{ old('precio', $producto->precio) }}" class='form-control'>
            @error('precio')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="peso">Peso</label>
            <input type="text" name="peso" placeholder="Peso" value="{{ old('peso', $producto->peso) }}" class='form-control'>
            @error('peso')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="categoria">Categoría</label>
            <input type="text" name="categoria" placeholder="Categoría" value="{{ old('categoria', $producto->categoria) }}" class='form-control'>
            @error('categoria')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="stock">Stock</label>
            <input type="text" name="stock" placeholder="Stock" value="{{ old('stock', $producto->stock) }}" class='form-control'>
            @error('stock')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="fecha_crea">Fecha Crea</label>
            <input type="text" name="fecha_crea" placeholder="Fecha Crea" value="{{ old('fecha_crea', $producto->fecha_crea) }}" class='form-control'>
            @error('fecha_crea')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <label for="fecha_ultima_venta">Fecha última venta</label>
            <input type="text" name="fecha_ultima_venta" placeholder="Fecha última venta" value="{{ old('fecha_ultima_venta', $producto->fecha_ultima_venta) }}" class='form-control'>
            @error('fecha_ultima_venta')
            <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
            @enderror
        </div>
        <div class="form-group">
            <input type="submit" value="Enviar" name="enviar" class='form-control btn btn-success'>
        </div>

resources/views/producto/index.blade.php
@extends('layouts.app')

@section('title', 'Productos | Konecta')

@section('content')

<h1>Productos</h1>

<p><a href="{{ url('/producto/create') }}" class="btn btn-success">Crear</a></p>

<table class='table table-hover'>

    <tr>
        <th class='table-primary'>Nombre</th>
        <th class='table-primary'>Referencia</th>
        <th class='table-primary'>Precio</th>
        <th class='table-primary'>Peso</th>
        <th class='table-primary'>Categoria</th>
        <th class='table-primary'>Stock</th>
        <th class='table-primary'>Fecha crea</th>
        <th class='table-primary'>Facha ultima venta</th>
        <th class='table-primary'></th>
    </tr>

    @foreach ($productos as $producto)
    <tr>
        <td>{{ $producto->nombre }}</td>
        <td>{{ $producto->referencia }}</td>
        <td>${{ number_format($producto->precio, 0, ',', '.') }}</td>
        <td>{{ $producto->peso }}</td>
        <td>{{ $producto->categoria }}</td>
        <td>{{ $producto->stock }}</td>
        <td>{{ $producto->fecha_crea }}</td>
        <td>{{ $producto->fecha_ultima_venta }}</td>
        <td>
            <a href="{{ route('producto.show', $producto) }}" class='btn btn-secondary'>Ver</a><br>
            <a href="{{ route('producto.edit', $producto) }}" class='btn btn-primary'>Editar</a><br>
            <form action="{{ route('producto.destroy', $producto) }}" method="post">
                @csrf
                {{ method_field('DELETE') }}
                <input type="submit" value="Eliminar" onclick="return confirm('Realmente desea eliminar este registro?')" class='btn btn-danger'>
            </form>
    </tr>
    @endforeach
</table>

<?= $productos->links(); ?>
@endsection

resources/views/producto/show.blade.php
@extends('layouts.app')

@section('title', 'Detalle Producto')

@section('content')

<h1>Producto <strong>{{ $producto->nombre }}</strong></h1>

<table class='table table-hover'>
    <tr>
        <th class='table-info'>Nombre</th>
        <td>{{ $producto->nombre }}</td>
    </tr>
    <tr>
        <th class='table-info'>Referencia</th>
        <td>{{ $producto->referencia }}</td>
    </tr>
    <tr>
        <th class='table-info'>Precio</th>
        <td>${{ number_format($producto->precio, 0, ',', '.') }}</td>
    </tr>
    <tr>
        <th class='table-info'>Peso</th>
        <td>{{ $producto->peso }}</td>
    </tr>
    <tr>
        <th class='table-info'>Categoría</th>
        <td>{{ $producto->categoria }}</td>
    </tr>
    <tr>
        <th class='table-info'>Stock</th>
        <td>{{ $producto->stock }}</td>
    </tr>
    <tr>
        <th class='table-info'>Fecha Crea</th>
        <td>{{ $producto->fecha_crea }}</td>
    </tr>
    <tr>
        <th class='table-info'>Fecha última venta</th>
        <td>{{ $producto->fecha_ultima_venta }}</td>
    </tr>
</table>

@endsection